[ASSIST-455] Task Management Updates
canyongbs/assist pull request #113
Opened 2023-09-22 19:19 UTC by mxm1070

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/455/

2023-09-23 16:50 UTC, Orrison requested changes
This looks great! If you could please update the Kanban view to display the task description in the card as well? Replacing the description dummy text I had there.

You will probably want to truncate that after a reasonable length.

2023-09-23 22:19 UTC, dgoetzit requested changes
Looks good! Just one minor change on my end.

2023-09-23 22:19 UTC, dgoetzit commented on app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php
> +                            ->getStateUsing(fn (Task $record) => $record->concern->{$record->concern::displayNameKey()})
We'll need to account for a potentially `null` concern here.

2023-09-25 15:06 UTC, mxm1070 commented
> This looks great! If you could please update the Kanban view to display the task description in the card as well? Replacing the description dummy text I had there.
> 
> You will probably want to truncate that after a reasonable length.

Done, and I set the limit to 50 characters.

2023-09-26 12:58 UTC, Orrison approved these changes

2023-09-26 13:00 UTC, merged