[ASSIST-553]: Build custom Tailwind CSS theme for ASSIST
canyongbs/assist pull request #131
Opened 2023-10-03 18:56 UTC by mxm1070

https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/553/

2023-10-03 20:09 UTC, danharrin requested changes

2023-10-03 20:09 UTC, danharrin commented on app/Providers/Filament/AdminPanelProvider.php
>          FilamentColor::register([
These colors should be registered outside of the panel, for things like the frontend form builder. Can we move it to either AppServiceProvider, or a new FilamentServiceProvider?

2023-10-03 20:09 UTC, danharrin commented on app/Providers/Filament/AdminPanelProvider.php
> +        //If you change colors here also change in tailwind.config
```suggestion
        // Changes to colors also need to be reflected in tailwind.config.js
```

2023-10-03 20:09 UTC, danharrin commented on tailwind.config.js
> +        //If you change colors here also change in AdminPanelProvider
```suggestion
        // Changes to colors also need to be reflected in AppServiceProvider
```

2023-10-04 16:37 UTC, danharrin approved these changes

2023-10-04 17:26 UTC, Orrison approved these changes

2023-10-04 17:26 UTC, merged